# Generated by Django 4.2.5 on 2023-10-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_delete_anm_algo_delete_ann_algo_delete_dt_algo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradientBoostingClassifier',
            fields=[
                ('Logistic_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Accuracy', models.TextField(max_length=100)),
                ('Precession', models.TextField(max_length=100)),
                ('F1_Score', models.TextField(max_length=100)),
                ('Recall', models.TextField(max_length=100)),
                ('Name', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'Gradient',
            },
        ),
    ]
